temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
con<-unz(temp,"household_power_consumption.txt")
dateDownloaded<-date()
powerData<-read.table(con,sep=";",header=TRUE)
subdata<-subset(powerData, Date=="1/2/2007" | Date=="2/2/2007")
subdata1<-subset(powerData, Date=="1/2/2007")
subdata2<-subset(powerData, Date=="2/2/2007")
Gap1<-subdata1[,2]
newGap<-sapply(Gap1,as.character)
newGap1<-sapply(strsplit(newGap,":"),function(x){x<-as.numeric(x);60*x[1]+x[2]})
Gap2<-subdata2[,2]
newGap<-sapply(Gap2,as.character)
newGap2<-sapply(strsplit(newGap,":"),function(x){x<-as.numeric(x);60*x[1]+x[2]}+1440)
newGap<-c(newGap1,newGap2)
Gap3<-subdata[,3]
newGap3<-sapply(Gap3,as.numeric)
newGap4<-t(t(newGap3)/1000)
Total<-data.frame(newGap,newGap4)
names(Total)<-c("Time","Global_active_power")
with(Total, plot(Time, Global_active_power, xlab ="", ylab="Global Active Power (kilowatts)", type='l',xaxt = 'n'))
axis(1, at=0, labels="Thurs")
axis(1, at=1440, labels="Fri")
axis(1, at=2880, labels="Sat")
dev.copy(png, file = "plot2.png")
dev.off()